version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_image
    container_name: jupyterhub_hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        #      - jupyterhub_data:/srv/jupyterhub
    environment:
      DOCKER_JUPYTER_CONTAINER: ${SINGLE_SERVER_IMAGE}
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub_hub
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PROJECT_DOMAIN}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_default"
    restart: on-failure

  jupyterlab:
    image: ${SINGLE_SERVER_IMAGE}
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo

  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}
    restart: on-failure

  oauth2_server:
    build: authentication
    container_name: c2o2b
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PROJECT_DOMAIN};PathPrefixStrip:/c2o2b/"
    restart: on-failure
